version: '3'

services:
  scrdesk-hbbs:
    container_name: scrdesk-hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r your-server-ip:21117
    volumes:
      - ./data:/root
    network_mode: host
    restart: unless-stopped
    environment:
      - RUST_LOG=info

  scrdesk-hbbr:
    container_name: scrdesk-hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: host
    restart: unless-stopped
    environment:
      - RUST_LOG=info
